### ISSUE TITLE
an awful yaml

### ISSUE THREAD

**Issue by nashby** [codebrawl/arnold#9]
I'm on the develop branch. 
`Post.create.edit` gives me this in my vim:

```
--- {created_at: ! '2011-08-24 19:23:55.710352217Z', name: !!null '', updated_at: ! '2011-08-24
    19:23:55.710352217Z'}
```

I really don't know why it broke down.
ruby 1.9.2-p290
rails 3.0.10 (3.0.7)

**Comment by razielgn** [comment]
Exactly what I said [here](https://github.com/codebrawl/arnold/commit/dda8a55557b24612483ddd630a4595670a68d255#commitcomment-542867). I think the problem is [here](https://github.com/codebrawl/arnold/blob/develop/lib/arnold.rb#L27), just setting everything that hasn't got a child to `FLOW` leads to this behavior: there should be a more sophisticated way to do it. Again, the Psych/Syck code is pure madness to play around with, so I wouldn't be surprised if we drop the prettiness until some other saner YAML implementation comes up.

**Comment by jeffkreeftmeijer** [comment]
Ok, let's revert the whole thing for now and think about it some more. I think these are the commits that introduced the whole thing: 24a4b3c7bcb6050444a8854c17ecf52f25e2c82f, dda8a55557b24612483ddd630a4595670a68d255 and b276f69c81b530a52b358d2cf3c3abee50107077. :)
